server: true
permalink: /:categories/:title/
exclude: ['node_modules', 'tamia', 'Gruntfile.coffee', '.gitignore', 'readme.md', 'wp', 'revealthecrowd.php']
excerpt_separator: <!--more-->

mega: 
  picurl: /o_O/